import React from 'react';
import './styles.css';
import Navbar from './components/navbar';
import SelectRol from './components/selectRol';
import MenuLogo from "./components/menuLogo";
import GotTop from './components/goTop';
import Footer from './components/footer';
class App extends React.Component{
  render(){
    return (
      <div>
        <header class="header-image">               
          <SelectRol></SelectRol>
          <MenuLogo></MenuLogo>                  
          <Navbar></Navbar>                                            
        </header>           
        <GotTop></GotTop>    
        <div class="content">          
          <h1>          
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaasaaaaaaaasaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa
            Aaaaaaaaaaaaaaaaaaa    
          </h1>
          <Footer></Footer>  
        </div>   
      </div>    
    );
  }
}

export default App;
